### ISSUE TITLE
miekg/dns

### ISSUE THREAD

**Issue by mld** [skx/dns-api-go#3]
Regarding 
> Because I couldn't find a decent DNS library.

Have you looked anything at [miekg/dns](https://github.com/miekg/dns)? 
Just letting you know of it in case you haven't.

**Comment by skx** [comment]
For completeness this is how I eventually solved the problem:

	for i, ent := range r.Answer {
		fmt.Printf("Answer %d\n", i)
		fmt.Printf("\tTTL : %d\n", ent.Header().Ttl)
		fmt.Printf("\tName : %s\n", ent.Header().Name)

		//
		// Lookup the value
		//
		switch ent.(type) {
		case *dns.AAAA:
			aaaa := ent.(*dns.AAAA).AAAA
			fmt.Printf("\tAAAA: %s\n", aaaa)
		case *dns.A:
			a := ent.(*dns.A).A
			fmt.Printf("\tA: %s\n", a)
		case *dns.MX:
			mx_name := ent.(*dns.MX).Mx
			mx_prio := ent.(*dns.MX).Preference
			fmt.Printf("\tMX: %d %s\n", mx_prio, mx_name)

I'm not in love with this, because it requires handling each case specially.  But it _does_ work, and would allow me to reinstate TTL fields.  I'll need to decide if I can clean it up and go this way or not.

**Comment by skx** [comment]
Resolved in 6a646abca4cb0be029d729a79863893f2aa3134d

**Comment by mld** [comment]
Sorry, it seems I didn't get the notification here until now. Agreed it's not fantastic to have to handle each RR differently. 

Not much of a Go coder myself (mostly a reader as of yet) but unless you've already seen it maybe miekg's dig-like query tool could help? https://github.com/miekg/exdns/blob/master/q/q.go
