### ISSUE TITLE
Can't do any PTR request

### ISSUE THREAD

**Issue by Uneo7** [skx/dns-api-go#5]
I'm trying to use the api to do PTR requests but it doesn't seems to work. 
I've tried online (https://dns-api.org) and with my own install and I alway get the same error  :
`{
     "error": "NXDOMAIN"
}`

When I try this request : https://dns-api.org/A/steve.fi I get the follwing ip address : 176.9.183.100 .
This ip address has a correctly configured PTR record (https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a172.217.22.130#) but the api can't find it (https://dns-api.org/PTR/176.9.183.100). My local install of the api return the same errors. 
I've also checked my DNS server with the nslookup command and it work : 

`nslookup 176.9.183.100
Server:         192.168.100.10
Address:        192.168.100.10#53

Non-authoritative answer:
100.183.9.176.in-addr.arpa      name = steve.fi.
`

**Comment by skx** [comment]
`PTR` lookups _do_ work, but they must be formatted appropriately.

For your example:

* https://dns-api.org/ptr/100.183.9.176.in-addr.arpa.

I can appreciate this might be non-obvious, and could be improved..

**Comment by skx** [comment]
And for IPv6:

* https://dns-api.org/ptr/0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.3.8.0.6.1.5.1.0.8.f.4.0.1.0.a.2.ip6.arpa.

**Comment by Uneo7** [comment]
Ok, I understand now. I agree it's not obvious, but my bad I should have tried this way. Maybe it could be useful to add a little reminder in the readme/doc.
