### ISSUE TITLE
How to use the dns-api-go in Graylog?

### ISSUE THREAD

**Issue by sojip** [skx/dns-api-go#6]
Hello @skx .
sorry for my english. i'm new in Graylog and i don't have too much knowledge in programmation. I saw that your dns-api-go can be use with Graylog to do a reverse dns lookup. 
if it is possible i will like to have explanation about the procedure.

Thank you

**Comment by skx** [comment]
This repository is an API for performing (lots of) DNS lookups, via `curl` or programatically.

I don't know anything about graylog, so I'm afraid I can suggest nothing useful beyond the example:

* lookup reverse DNS for 176.9.183.100:
   * `curl https://dns-api.org/ptr/100.183.9.176.in-addr.arpa.`

**Comment by sojip** [comment]
ok. Thanks

**Comment by ayush1023** [comment]
I want to perform reverse lookup query from my graylog server to domain controller. Can any one guide me ?
