### ISSUE TITLE
Facing the problems regarding with dns-api-go

### ISSUE THREAD

**Issue by sharathb1993** [skx/dns-api-go#7]
Hi,

I created Ubuntu virtual machine on that i created the Go environment after that i successfully imported and installed the skx/dns-api-go. i followed these doc : https://github.com/skx/dns-api-go for to setup the environment also i installed the required dependencies like Dancer,Plack::Middle ware::Throttle::Lite,Net::DNS::Resolver,twiggy, libdancer-perl ,libnet-cidr-lite-perl , libplack-middleware-reverseproxy-perl.

after that at last i run the following command : dns-api-go -redis-server localhost:6379

then am getting the following result :

Launching the server on http://127.0.0.1:9999 redis: 2018/09/25 11:18:56 ring.go:263: ring shard state changed: Redis is down.

when i changed the port number in web preview in cloud shell it is showing as your server is not listing to 6379 port number, but in the instance level when i run the netstat -an command it is showing as the server is listing for 6379 port

please help me in resolving these issue.

﻿

**Comment by skx** [comment]
> Hi, I created Ubuntu virtual machine on that i created the Go environment  after that i successfully imported and installed the skx/dns-api-go. i  followed these doc : https://github.com/skx/dns-api-go  

That's good.

> for to setup the environment also i installed the required dependencies  like Dancer,Plack::Middle  ware::Throttle::Lite,Net::DNS::Resolver,twiggy, libdancer-perl  ,libnet-cidr-lite-perl , libplack-middleware-reverseproxy-perl.

Those dependencies are __not__ required.  They were required for the previous version of this software, written in perl, which is available here:

* https://github.com/skx/dns-api.org

> after that at last i run the following command : dns-api-go -redis-server localhost:6379 then am getting the following result : 
> > Launching the server on http://127.0.0.1:9999 
> > redis: 2018/09/25 11:18:56 ring.go:263: ring shard state changed: Redis is down. 

You launched the server, it started, and is available on http://127.0.0.1:9999/ however the output you see shows that _redis_ is not running.

>when i changed the port number in web preview in cloud shell it is  showing as your server is not listing to 6379 port number, but in the  instance level when i run the netstat -an command it is showing as the  server is listing for 6379 port please help me in resolving these issue.

I'm confused by this.  The output shows that the server is listening on 127.0.0.1:9999 (i.e. port 9999).  You've launched the server with "-redis-server " flag, which should point ot the address of a running redis server.

As redis is not running you should either :

* Launch this software without the redis server:
   * `dns-api-go`
* Install & start redis, which will listen upon 127.0.0.1:6379.
  * Then restart dns-api-go, which will connect to it.

**Comment by skx** [comment]
This sounds like a problem with cloud-shell, or your VM setup.

The server is __only__ listening on 127.0.0.1 which will __not__ be externally accessible.

It should be accessible internally, like so:

      $ dns-api-go &
      $ curl http://127.0.0.1:9999/a/steve.fi

If that works then the server is running, and available.

If you want to connect form outside the host you'll have to start with a host:
 
      $ dns-api-go -host 0.0.0.0

**Comment by sharathb1993** [comment]
also my server is listening on 127.0.0.1:6379 
![image](https://user-images.githubusercontent.com/43539206/46071076-de186600-c19c-11e8-9745-a73971b51471.png)

**Comment by sharathb1993** [comment]
as you said in previous comment i run those commands and working fine but am getting these error:
![image](https://user-images.githubusercontent.com/43539206/46071368-7c0c3080-c19d-11e8-83c3-65c3eb56fedd.png)

**Comment by skx** [comment]
If you get "address already in use" you need to stop the command that is already running.

Really though I cannot offer much help/support for cloud-services; you're not describing a bug here, you're describing a networking problem with your environment.  An environment I have no experience with, and which I cannot see.

* If you want to use redis then redis must be running.
* If you want to access the dns-api-server externally you must either
  * Launch it with "-host 0.0.0.0".
  * Or setup forwarding-rules appropriately.

**Comment by sharathb1993** [comment]
thanks for your support. i will check the network issues in cloud
