### ISSUE TITLE
Consider reporting 404 or [] for NXDOMAIN

### ISSUE THREAD

**Issue by LEW21** [skx/dns-api-go#9]
When we send a request to check a domain that has records, the response is a list of records - for example https://dns-api.org/MX/gmail.com:
```
[
  {
    "name": "gmail.com.",
    "ttl": "2513",
    "type": "MX",
    "value": "20\talt2.gmail-smtp-in.l.google.com."
  },
  ...
]
```

However, when there are no records, we get a single object with the error property - for example https://dns-api.org/MX/example.com:
```
{
  "error": "NXDOMAIN"
}
```

This makes error handling a bit strange - as we don't know if we're getting an array or an object before we parse the response; and it's not obvious that all objects are going to be errors.

APIs commonly use HTTP errors to report errors, and NXDOMAIN has the same semantics as the HTTP 404 error. This way - if we get 200, we'll automatically know that we've got a non-empty list of results, that we can always parse as a list.

Another idea would be to report an empty list `[]` in case of NXDOMAIN - however, in this case we won't have space to describe the error. OTOH "NXDOMAIN" is not too descriptive.

**Comment by skx** [comment]
Good idea; 404 will be returned in the case of no errors.

**Comment by LEW21** [comment]
Thanks!
